
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql
    container_name: 'my'

#services:
#
#  db:
#    image: postgres
#    restart: always
#    # set shared memory limit when using docker compose
#    shm_size: 128mb
#    # or set shared memory limit when deploy via swarm stack
#    volumes:
#      - ./db/:/var/lib/postgresql
#    #  - type: tmpfs
#    #    target: /dev/shm
#    #    tmpfs:
#    #      size: 134217728 # 128*2^20 bytes = 128Mb
#    environment:
#      POSTGRES_PASSWORD: postgres
#    container_name: 'my_postgres'
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
#    container_name: 'adminer'



