[DEFAULT]
sources = .\migrations\
migration_table = _yoyo_migration
batch_mode = off
verbosity = 0
database = postgresql://postgres:postgres@localhost

# pip install yoyo-migrations
# yoyo new .\migration -m "Add column color" - создать миграцию
# В steps[] написать нужные sql-команды на исполнение
# Необходимо прописать путь до БД в файле yoyo.ini
# yoyo apply - запустить миграцию

# yoyo rollback - откатить миграцию